---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy: 
      fail-fast: false

      matrix:
        version_branch: [10]

    steps:
      - name: Checkout out the codebase
        uses: actions/checkout@v3

      - name: Test building image
        run: podman build -t docker-debian-ansible:${{ matrix.version_branch }} ./debian${{ matrix.version_branch }}/.
      
      - name: Run the built image
        run: podman run --name test-container --detach --privileged --volume /sys/fs/cgroup:/sys/fs/cgroup:ro docker-debian-ansible:${{ matrix.version_branch }}

      - name: Verify Ansible is accessible in the built image
        run: podman exec --tty test-container env TERM=xterm ansible --version